---

- name: Logging | Assures {{ kube_addons_dir }}/cluster-logging dir exists
  file: path={{ kube_addons_dir }}/cluster-logging state=directory

- name: Logging | Copy logging yaml files to master
  template:
  args:
    src: "cluster-logging/{{ item }}.j2"
    dest: "{{ kube_addons_dir }}/cluster-logging/{{ item }}"
    mode: 0644
    owner: root
    group: root
  with_items:
    - es-controller.yaml
    - es-service.yaml
    - kibana-controller.yaml
    - kibana-service.yaml
    - fluentd-daemonset.yaml
