---
# Tasks for installing kubernetes addons.

#
# Determine init system.

- name: Determine addons_use_upstart
  set_fact:
    addons_use_upstart: false

- set_fact:
    addons_use_upstart: true
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int < 15

- name: Create addons directory
  file: path={{ kube_addons_dir }} state=directory

- include: nfs.yml
  when: nfs_setup

- include: addons-install.yml
  when: not use_addon_manager

- include: addon-manager.yml
  when: use_addon_manager
