apiVersion: v1
kind: Pod
metadata:
  name: master-nginx
  labels:
    k8s-app: master-nginx
spec:
  hostNetwork: true
  containers:
  - name: master-nginx
    image: {{ common_image_nginx }}
    volumeMounts:
    - name: caicloudapp-certs
      mountPath: /etc/nginx/ssl
    - name: nginx-conf
      mountPath: /etc/nginx/caicloud
    args:
    - nginx
    - -g
    - "daemon off;"
    - -c
    - /etc/nginx/caicloud/nginx.conf
  volumes:
  - name: caicloudapp-certs
    hostPath:
      path: /etc/kubernetes/caicloudapp_certs
  - name: nginx-conf
    hostPath:
      path: /etc/kubernetes/nginx
