---
# Common tasks for all other roles.

- name: Get flannel interface name of IPv4 address
  shell: ip addr show | grep {{ internal_ip }} | awk '{print $NF}'
  register: interface_name
  changed_when: false

- name: Set flannel interface
  set_fact:
    flannel_interface: "{{ interface_name.stdout }}"
  changed_when: false
  when: networking == "flannel"

- name: Determine kubernetes_use_upstart
  set_fact:
    kubernetes_use_upstart: false

- set_fact:
    kubernetes_use_upstart: true
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int < 15

- name: Display system information
  debug: msg="{{ ansible_distribution }} {{ ansible_distribution_version }}"
