---
# Common tasks for all other roles.

- name: Create the directory used to store binaries
  file: path={{ bin_dir }} state=directory

- name: Create ansible temp directory
  file: path={{ ansible_temp_dir }} state=directory

- name: Get interface name of IPv4 address stored in ansible_host
  shell: ip addr show | grep {{ ansible_host }} | awk '{print $NF}'
  register: interface_name
  changed_when: false

- name: Set all interfaces by {{ interface_name.stdout }} according to ansible_host
  set_fact:
    etcd_interface: "{{ interface_name.stdout }}"
    flannel_interface: "{{ interface_name.stdout }}"
    kube_apiserver_advertise_interface: "{{ interface_name.stdout }}"
    kubelet_node_ip_interface: "{{ interface_name.stdout }}"
  changed_when: false

- name: Determin kubernetes_use_upstart
  set_fact:
    kubernetes_use_upstart: false

- set_fact:
    kubernetes_use_upstart: true
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int < 15

- name: Display system information
  debug: msg="{{ ansible_distribution }} {{ ansible_distribution_version }}"
