---
# Common tasks for all other roles.

- name: Create the directory used to store binaries
  file: path={{ bin_dir }} state=directory

- name: Create ansible temp directory
  file: path={{ ansible_temp_dir }} state=directory

- name: Get flannel interface name of IPv4 address
  shell: ip addr show | grep {{ ansible_host }} | awk '{print $NF}'
  register: interface_name
  changed_when: false

- name: Set flannel interface
  set_fact:
    flannel_interface: "{{ interface_name.stdout }}"
  changed_when: false
  when: networking == "flannel"

- name: Determine kubernetes_use_upstart
  set_fact:
    kubernetes_use_upstart: false

- set_fact:
    kubernetes_use_upstart: true
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int < 15

- name: Display system information
  debug: msg="{{ ansible_distribution }} {{ ansible_distribution_version }}"

- name: CentOS | Be sure libselinux-python are installed
  yum: name=libselinux-python
  when: ansible_distribution == "CentOS"
