apiVersion: v1
kind: Pod
metadata:
  name: fluentd-elasticsearch
  namespace: kube-system
spec:
  containers:
  - name: fluentd-elasticsearch
    image: index.caicloud.io/caicloudgcr/google_containers_fluentd-elasticsearch:1.11
    resources:
      limits:
        cpu: 100m
    args:
    - -q
    volumeMounts:
    - name: varlog
      mountPath: /var/log
    - name: containerlog
      mountPath: /var/log/containers
    - name: varlibdockercontainers
      mountPath: /var/lib/docker/containers
      readOnly: true
  terminationGracePeriodSeconds: 30
  volumes:
  - name: varlog
    hostPath:
      path: /var/log/upstart
  - name: containerlog
    hostPath:
      path: /var/log/containers
  - name: varlibdockercontainers
    hostPath:
      path: /var/lib/docker/containers
