apiVersion: v1
kind: Pod
metadata:
  name: master-nginx
spec:
  hostNetwork: true
  containers:
  - name: master-nginx
    image: {{ pillar['master_nginx_image'] }}
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 200Mi
    volumeMounts:
    - name: caicloudapp-certs
      mountPath: /etc/nginx/ssl
    - name: nginx-conf
      mountPath: /etc/nginx/caicloud
    args:
    - nginx
    - -g
    - "daemon off;"
    - -c
    - /etc/nginx/caicloud/nginx.conf
  volumes:
  - name: caicloudapp-certs
    hostPath:
      path: /etc/kubernetes/caicloudapp_certs
  - name: nginx-conf
    hostPath:
      path: /etc/kubernetes/nginx
