---
# Generate kubeconfig for control maichine.

- name: Copy the cmkubeconfig gen script
  copy:
    src=kube-gen-cmkubeconfig.sh
    dest={{ kube_script_dir }}
    mode=0500
  changed_when: false

- name: Set default dns host name
  set_fact:
    host_name: "cluster"

- name: Set user defined dns host name
  set_fact:
    host_name: "{{ dns_host_name }}"
  when: dns_host_name is defined

- name: Set default base domain name
  set_fact:
    domain_name: "{{ caicloud_private_test_domain }}"

- name: Set caicloud app domain name
  set_fact:
    domain_name: "{{ caicloud_app_domain }}"
  when: host_provider == 'anchnet' or host_provider == 'aliyun'

- name: Set user defined domain name
  set_fact:
    domain_name: "{{ base_domain_name }}"
  when: base_domain_name is defined

- name: Set the final domain name
  set_fact:
    kube_cert_ip_or_domain: "{{ host_name }}.{{ domain_name }}"

- name: Generate kubeconfig for control machine
  command: "{{ kube_script_dir }}/kube-gen-cmkubeconfig.sh"
  environment:
    TOKEN_DIR: "{{ kube_token_dir }}"
    CM_KUBECONFIG: "{{ cm_kubectl_kubeconfig }}"
    MASTER_IP: "{{ kube_cert_ip_or_domain }}"
    CERT_DIR: "{{ kube_cert_dir }}"
    CA_CERT_DIR: "{{ caicloudapp_cert_dir }}"
    CONTEXT: "{{ host_provider }}_{{ cluster_name }}"
