---
# Generate kubeconfig for control maichine.

- name: Copy the cmkubeconfig gen script
  copy:
    src=kube-gen-cmkubeconfig.sh
    dest={{ kube_script_dir }}
    mode=0500
  changed_when: false

- name: Set the final domain name
  set_fact:
    kube_cert_ip_or_domain: "{{ dns_host_name }}.{{ base_domain_name }}"

- name: Generate kubeconfig for control machine
  command: "{{ kube_script_dir }}/kube-gen-cmkubeconfig.sh"
  environment:
    TOKEN_DIR: "{{ kube_token_dir }}"
    CM_KUBECONFIG: "{{ cm_kubectl_kubeconfig }}"
    MASTER_IP: "{{ kube_cert_ip_or_domain }}"
    CERT_DIR: "{{ kube_cert_dir }}"
    CA_CERT_DIR: "{{ caicloudapp_cert_dir }}"
    CONTEXT: "{{ host_provider }}_{{ cluster_name }}"
