---
# Install/upgrade kubernetes master.

- name: Install kubernetes master
  include: install.yml
  when: k8s_op == "OP_INSTALL"

- name: Upgrade kubernetes master
  include: upgrade.yml
  when: k8s_op == "OP_UPGRADE"
