---
# Install ubuntu upstart files.

- name: Upstart | Write upstart config files
  copy:
    src=init_conf/{{ item }}.conf
    dest=/etc/init/{{ item }}.conf
  register: "{{ item }}_config"
  notify:
    - restart daemons
  with_items:
    - kubelet

- copy:
    src=init_conf/{{ item }}.conf
    dest=/etc/init/{{ item }}.conf
  register: "{{ item }}_config"
  notify:
    - restart daemons
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
    - kube-proxy
  when: not use_hyperkube

- name: Upstart | Write upstart script files
  copy:
    src=init_scripts/{{ item}}
    dest=/etc/init.d/{{ item }}
  register: "{{ item }}_service"
  notify:
    - restart daemons
  with_items:
    - kubelet

- copy:
    src=init_scripts/{{ item}}
    dest=/etc/init.d/{{ item }}
  register: "{{ item }}_service"
  notify:
    - restart daemons
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
    - kube-proxy
  when: not use_hyperkube

- name: Upstart | Write kubernetes master default files
  template: src={{ item }}-default.j2 dest="/etc/default/{{ item }}"
  register: "{{ item }}_default"
  notify:
    - restart daemons
  with_items:
    - kubelet

- template: src={{ item }}-default.j2 dest="/etc/default/{{ item }}"
  register: "{{ item }}_default"
  notify:
    - restart daemons
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
    - kube-proxy
  when: not use_hyperkube
