apiVersion: v1
kind: Pod
metadata:
  name: fluentd-elasticsearch
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
    kubernetes-admin.caicloud.io/type: application
    kubernetes-admin.caicloud.io/application: fluentd-elasticsearch
spec:
  containers:
  - name: fluentd-elasticsearch
    image: {{ fluentd_elasticsearch_image }}
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
      requests:
        cpu: 20m
        memory: 200Mi
    args:
    - -q
    volumeMounts:
    - name: varlog
      mountPath: /var/log
    - name: containerlog
      mountPath: /var/log/containers
    - name: varlibdockercontainers
      mountPath: /var/lib/docker/containers
      readOnly: true
  terminationGracePeriodSeconds: 30
  volumes:
  - name: varlog
    hostPath:
      path: /var/log
  - name: containerlog
    hostPath:
      path: /var/log/containers
  - name: varlibdockercontainers
    hostPath:
      path: /var/lib/docker/containers
