---
# Install docker on centos.
#

- name: CentOS | Stop and mask the firewalld service
  command: "{{ item }}"
  with_items:
    - systemctl daemon-reexec
    - systemctl stop firewalld
    - systemctl mask firewalld
  ignore_errors: True
  failed_when: False

- name: CentOS | Install the iptables-services
  yum: name=iptables-services

- name: CentOS | Enable the iptable service
  command: "{{ item }}"
  with_items:
    - systemctl enable iptables
    - systemctl daemon-reload
    - systemctl start iptables
    - iptables -F

- name: CentOS | Install GPG key
  template: src="yum-docker.repo" dest="/etc/yum.repos.d/docker.repo"

- name: CentOS | Install specific version of docker engine
  yum: name={{ item }}
  with_items:
    - docker-engine-{{ docker_version }}
    - device-mapper-event
    - device-mapper-event-devel

- name: Reload systemd manager configuration
  command: systemctl daemon-reload
