---
# Install docker on centos.
#

- name: CentOS | Check if firewalld service exists
  set_fact:
    firewalld_existing: True
- command: systemctl status firewalld
  register: output
  failed_when: False
- set_fact:
    firewalld_existing: False
  when: output.stdout.find("not-found") != -1

- name: CentOS | Stop and mask the firewalld service
  command: "{{ item }}"
  with_items:
    - systemctl daemon-reexec
    - systemctl stop firewalld
    - systemctl mask firewalld
  when: firewalld_existing

- name: CentOS | Install the iptables
  yum: name=iptables

- name: CentOS | Clear iptables
  command: iptables -F

- name: CentOS | Install GPG key
  template: src="yum-docker.repo" dest="/etc/yum.repos.d/docker.repo"

- name: Finds incomplete or aborted yum transactions on a system and attempts to complete them
  command: yum-complete-transaction --cleanup-only
  failed_when: False

- name: CentOS | Install specific version of docker engine
  yum: name={{ item }}
  with_items:
    - docker-engine-{{ docker_version }}
    - device-mapper-event
    - device-mapper-event-devel

- name: Reload systemd manager configuration
  command: systemctl daemon-reload
