---
# Install docker on ubuntu.
#

- name: Ubuntu | Install GPG key
  apt_key: keyserver=keyserver.ubuntu.com id=F76221572C52609D
  # Register and retry to work around transient http issues
  register: gpg_key_install
  until: gpg_key_install|success
  retries: 5
  delay: 3

- name: Ubuntu | Configure apt mirror
  template: src="apt-mirror.list.j2" dest="/etc/apt/sources.list"

- name: Ubuntu | Configure docker apt repository
  template: src="apt-docker.list.j2" dest="/etc/apt/sources.list.d/docker.list"

- name: Ubuntu | Update repository cache
  apt: update_cache=yes
  # Register and retry to work around transient http issues
  register: apt_cache_update
  until: apt_cache_update|success
  retries: 3
  delay: 5

- name: Ubuntu | Install specific version of docker engine
  apt: name=docker-engine={{ docker_version }}-0~{{ ansible_distribution_release }}
