---
# Get aliyun instances ssh info.

- name: Set common parametes
  set_fact:
    common_paras: "--AccessKeyId {{ access_key_id }} --AccessKeySecret {{ access_key_secret }} --RegionId {{ region_id }} --output json"

- name: Search the security group by name
  command: aliyuncli ecs DescribeSecurityGroups {{ common_paras }} --SecurityGroupName {{ security_group_name }}
  register: sg_info
  until: sg_info.stdout.find("Code") == -1
  retries: 5
  delay: 5

- name: Get security group id from an existing cluster
  set_fact:
    json_sg_info: "{{ sg_info.stdout | from_json }}"
- fail: msg="Failed to get security group ID"
  when: json_sg_info.TotalCount|int == 0
- set_fact:
    aliyun_sgid: "{{ json_sg_info.SecurityGroups.SecurityGroup[0].SecurityGroupId }}"
  when: json_sg_info.TotalCount|int > 0

- name: Delete old instance.master
  file: path={{ playbook_dir }}/instance.master state=absent
  changed_when: False

- name: Touch instance.master
  file: path={{ playbook_dir }}/instance.master state=touch
  changed_when: False

- name: Delete old instance.node
  file: path={{ playbook_dir }}/instance.node state=absent
  changed_when: False

- name: Touch instance.node
  file: path={{ playbook_dir }}/instance.node state=touch
  changed_when: False

- name: Run master instances
  include: get-ssh-info.yml
  vars:
    instance_name: "{{ master_name_prefix }}{{ item }}"
    save_to_file: "{{ playbook_dir }}/instance.master"
  with_sequence: count={{ master_node_num }}

- name: Run node instances
  include: get-ssh-info.yml
  vars:
    instance_name: "{{ node_name_prefix }}{{ item }}"
    save_to_file: "{{ playbook_dir }}/instance.node"
  with_sequence: count={{ minion_node_num }}
