---
# This playbook destroy aliyun instances by aliyuncli tool.

- name: Config for aliyuncli
  hosts: localhost
  become: yes
  roles:
    - aliyuncli
  tags:
    - aliyuncli

- name: Add domain name to dns
  hosts: localhost
  become: yes
  roles:
    - dns
  tags:
    - dns

- name: Stop aliyun instances
  hosts: localhost
  become: yes
  roles:
    - down
  tags:
    - down
