# Copyright 2016 The Kubernetes Authors All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM BASEIMAGE

# Used for alpine.
# RUN apk add --update iptables ethtool ca-certificates file util-linux socat curl conntrack-tools \
# 	&& rm -rf /var/cache/apk/*

RUN sed -i "s/httpredir.debian.org/mirrors.163.com/g" /etc/apt/sources.list && \
	DEBIAN_FRONTEND=noninteractive apt-get update -y \
    && DEBIAN_FRONTEND=noninteractive apt-get -yy -q install \
    iptables \
    ebtables \
    ethtool \
    ca-certificates \
    conntrack \
    util-linux \
    socat \
    git \
    jq \
    nfs-common \
    glusterfs-client \
    cifs-utils \
    file \
    curl \
    && DEBIAN_FRONTEND=noninteractive apt-get upgrade -y \
    && DEBIAN_FRONTEND=noninteractive apt-get autoremove -y \
    && DEBIAN_FRONTEND=noninteractive apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* # CACHEBUST

RUN cp /usr/bin/nsenter /nsenter

ADD hyperkube /hyperkube
