---

- name: reload systemd
  command: systemctl --system daemon-reload
  notify:
    - restart daemons
  when: not (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int < 15)

- name: restart daemons
  command: /bin/true
  notify:
    - restart apiserver
    - restart controller-manager
    - restart scheduler
    - restart kubelet

- name: restart apiserver
  service: name=kube-apiserver state=restarted
  when: apiserver_started.changed == false

- name: restart controller-manager
  service: name=kube-controller-manager state=restarted
  when: controller_manager_started.changed == false

- name: restart scheduler
  service: name=kube-scheduler state=restarted
  when: scheduler_started.changed == false

- name: restart kubelet
  service: name=kubelet state=restarted
  when: master_kubelet_started.changed == false
