---
# Fetch kubeconfig

- name: Create kubeconfig file directory
  file: path={{ ansible_env.HOME }}/.kube state=directory

- name: Set kubeconfig name for control machine according to uid and cid
  set_fact:
    kubeconfig_name: "config_{{ cluster_name }}"

- name: Fetch kubeconfig for kubectl from master
  fetch: src={{ kubectl_kubeconfig }} dest={{ ansible_env.HOME }}/.kube/{{ kubeconfig_name }} flat=yes
  delegate_to: "{{ groups['masters'][0] }}"

- name: Remove .kube/config in {{ ansible_env.HOME }} directory
  file: path={{ ansible_env.HOME }}/.kube/config state=absent
  changed_when: false

- name: Create .kube/config soft link in {{ ansible_env.HOME }} directory
  file: path={{ ansible_env.HOME }}/.kube/config src={{ ansible_env.HOME }}/.kube/{{ kubeconfig_name }} state=link
