---
# Stop a instance
#
# Assumed vars:
#   instance_id

- set_fact:
    do_stop: True

- name: Check if the instance {{ instance_id }} is in Stopping or Stopped status
  command: aliyuncli ecs DescribeInstances {{ common_paras }} --ZoneId {{ zone_id }} --SecurityGroupId {{ aliyun_sgid }} --InstanceIds '["{{ instance_id }}"]'
  register: check_output
  until: check_output.stdout.find("Code") == -1
  retries: 5
  delay: 5

- set_fact:
    do_stop: False
  when: check_output.stdout.find("Stopping") != -1 or check_output.stdout.find("Stopped") != -1

# Send StopInstance signal, When succeeded, no 'Code' find in stdout
- name: Stop instance
  command: aliyuncli ecs StopInstance {{ common_paras }} --InstanceId {{ instance_id }}
  register: result
  until: result.stdout.find("Code") == -1
  retries: 5
  delay: 5
  when: do_stop
