---
# This playbook deploys kubernetes cluster on caicloud supported platforms.

- name: Precheck for loadbalancer
  hosts:
    - resourceservers
    - nodes
    - localhost
  become: yes
  roles:
    - loadbalancer
  tags:
    - loadbalancer

- name: Setup for offline
  hosts:
    - resourceservers
    - nodes
  become: yes
  roles:
    - role: offline
      when: offline_mode
  tags:
    - offline

- name: Prologue once
  hosts:
    - resourceservers
    - nodes
  become: yes
  roles:
    - prologue-once
  tags:
    - prologue-once

- name: Install etcd
  hosts: etcd
  become: yes
  roles:
    - etcd
  tags:
    - etcd

- name: Install docker
  hosts: all
  become: yes
  roles:
    - docker
  tags:
    - docker

- name: Install flannel
  hosts:
    - masters
    - nodes
  become: yes
  roles:
    - { role: flannel, when: networking == 'flannel' }
  tags:
    - network-service
    - flannel

- name: Install calico
  hosts:
    - masters
    - nodes
  become: yes
  roles:
    - { role: calico, when: networking == 'calico' }
  tags:
    - network-service
    - calico

- name: Install kubernetes masters
  hosts: masters
  become: yes
  roles:
    - master
  tags:
    - masters

- name: Install kubeconfig for kubectl and add dns to hosts
  hosts:
    - localhost
  become: yes
  roles:
    - control-machine
  tags:
    - control-machine

- name: Install kubernetes nodes
  hosts: nodes
  become: yes
  roles:
    - node
  tags:
    - nodes

- name: Generate configmap
  hosts: localhost
  become: yes
  roles:
    - { role: /addon-manager/configmap, when: generate_configmap }
  tags:
    - configmap

- name: Install kubernetes addons
  hosts: masters
  become: yes
  roles:
    - kubernetes-addons
  tags:
    - addons

- name: Install runtime dependencies and manifests
  hosts:
    - masters
    - nodes
  become: yes
  roles:
    - epilogue
  tags:
    - epilogue
    - addons
