---
# This playbook upgrade/downgrade kubernetes cluster on caicloud supported platforms.

- name: Precheck for loadbalancer
  hosts:
    - resourceservers
    - nodes
    - localhost
  become: yes
  roles:
    - loadbalancer
  tags:
    - loadbalancer

- name: Setup for offline
  hosts:
    - resourceservers
    - nodes
  become: yes
  roles:
    - role: offline
      when: offline_mode
  tags:
    - offline

- name: Prologue once
  hosts:
    - resourceservers
    - nodes
  become: yes
  roles:
    - prologue-once
  tags:
    - prologue-once

- name: Upgrade/downgrade masters
  hosts: masters
  become: yes
  roles:
    - master
  tags:
    - masters

- name: Upgrade/downgrade nodes
  hosts: nodes
  become: yes
  roles:
    - node
  tags:
    - nodes

- name: Record operation log
  hosts:
    - masters
    - nodes
  become: yes
  roles:
    - epilogue
  tags:
    - epilogue

# Because after updated to new version, we need the new kubectl binary.
- name: Fetch kubectl and kubeconfig
  hosts:
    - localhost
  become: yes
  roles:
    - control-machine
  tags:
    - control-machine
