---
# Generate basic auth to login to kubernetes cluster via http.

- name: Copy the basic auth gen script
  copy:
    src=kube-gen-basic-auth.sh
    dest={{ kube_script_dir }}
    mode=0500
  changed_when: false

- name: Generate basic auth for apiserver 
  command: "{{ kube_script_dir }}/kube-gen-basic-auth.sh"
  args:
    creates: "{{ kube_token_dir }}/basic-auth.csv"
  environment:
    TOKEN_DIR: "{{ kube_token_dir }}"
    USER_NAME: "{{ kube_user }}"
    PASSWORD: "{{ kube_password }}"

- name: Verify basic auth permissions
  file:
    path={{ kube_token_dir }}/basic-auth.csv
    group={{ kube_cert_group }}
    owner=kube
    mode=0440
  notify:
    - restart apiserver
