---
# Generate self-signed certificates.
# TODO: This only generates a cert for one master.

- name: Install openssl for easy-rsa stuff
  package: name={{ item }} state=latest
  with_items:
    - openssl
    - curl

- name: Copy easy-rsa.tar.gz from local copy
  copy:
    src=easy-rsa.tar.gz
    dest={{ kube_script_dir }}

- name: Overwrite make-ca-cert.sh from local copy
  copy:
    src=make-ca-cert.sh
    dest={{ kube_script_dir }}
    mode=0500
  changed_when: false

- name: Run create cert script on master
  command:
    "{{ kube_script_dir }}/make-ca-cert.sh"
  args:
    creates: "{{ kube_cert_dir }}/server.crt"
  environment:
    SCRIPT_DIR: "{{ kube_script_dir }}"
    MASTER_IP: "{{ kube_cert_ip }}"
    MASTER_NAME: "{{ inventory_hostname }}"
    DNS_DOMAIN: "{{ dns_domain }}"
    SERVICE_CLUSTER_IP_RANGE: "{{ kube_service_addresses }}"
    CERT_DIR: "{{ kube_cert_dir }}"
    CERT_GROUP: "{{ kube_cert_group }}"
    HTTP_PROXY: "{{ http_proxy|default('') }}"
    HTTPS_PROXY: "{{ https_proxy|default('') }}"

- name: Verify certificate permissions
  file:
    path={{ item }}
    group={{ kube_cert_group }}
    owner=kube
    mode=0440
  with_items:
    - "{{ kube_cert_dir }}/ca.crt"
    - "{{ kube_cert_dir }}/server.crt"
    - "{{ kube_cert_dir }}/server.key"
    - "{{ kube_cert_dir }}/kubecfg.crt"
    - "{{ kube_cert_dir }}/kubecfg.key"
