---
# Generate abac policy to controll access

- name: Copy the abac policy generic gen script
  copy:
    src=kube-gen-abac-policy-generic.sh
    dest={{ kube_script_dir }}
    mode=0500
  changed_when: false

- name: Generate abac policy generic
  command: "{{ kube_script_dir }}/kube-gen-abac-policy-generic.sh"
  environment:
    TOKEN_DIR: "{{ kube_token_dir }}"
  notify:
    - restart apiserver

- name: Copy the abac policy gen script
  copy:
    src=kube-gen-abac-policy.sh
    dest={{ kube_script_dir }}
    mode=0500
  changed_when: false

- name: Generate abac policy for master components
  command: "{{ kube_script_dir }}/kube-gen-abac-policy.sh {{ item[0] }}-{{ item[1] }}"
  environment:
    TOKEN_DIR: "{{ kube_token_dir }}"
  with_nested:
    - [ "system:controller_manager", "system:scheduler", "system:kubectl", "system:kubelet", "system:proxy" ]
    - "{{ groups['masters'] }}"
  notify:
    - restart apiserver

- name: Generate abac policy for node components
  command: "{{ kube_script_dir }}/kube-gen-abac-policy.sh {{ item[0] }}-{{ item[1] }}"
  environment:
    TOKEN_DIR: "{{ kube_token_dir }}"
  with_nested:
    - [ 'system:kubelet', 'system:proxy' ]
    - "{{ groups['nodes'] }}"
  notify:
    - restart apiserver
