---
# Generate basic auth to login to kubernetes cluster via http.

- name: Copy the basic auth gen script
  copy:
    src=kube-gen-basic-auth.sh
    dest={{ kube_script_dir }}
    mode=0500
  changed_when: false

- name: Generate basic auth for apiserver 
  command: "{{ kube_script_dir }}/kube-gen-basic-auth.sh"
  environment:
    TOKEN_DIR: "{{ kube_token_dir }}"
    USER_NAME: "{{ kube_user }}"
    PASSWORD: "{{ kube_password }}"
  notify:
    - restart apiserver
