---
# Base kubernetes tasks for all masters/nodes, including:
#  - create various directories (see defaults/main.yml)
#  - write global config file
#  - download and link all kubernetes binaries
#  - generate certs and tokens
#
# Notes about configurations:
# - For upstart, components' configurations are located at /etc/default/$name; which
#   loads its configs from /etc/kubernetes/ directory.
# - For systemd, components' configurations are written directly in unit files, i.e.
#   /etc/systemd/system/$name; which also loads its configs from /etc/kubernetes/.

#
# Config time zone

- name: Update time zoneinfo
  command: "{{ item }}"
  with_items:
    - rm -f /etc/localtime
    - cp -f /usr/share/zoneinfo/{{ time_zoneinfo }} /etc/localtime

#
# Setup chrony for time synchronization

- name: Setup chrony
  include: chrony.yml

#
# Set docker container log rotation.

- name: Set docker container log rotation
  include: configure-logging.yml

#
# Disable swap.

- name: Turn off swap
  command: swapoff -a
  failed_when: false

- name: Disable swap permanently
  replace:
    dest: /etc/fstab
    regexp: '(^[^#].*\s+swap\s+.*$)'
    replace: '#\1'

#
# Make sure directories exist.

- name: Create directories
  file: path={{ item }} state=directory
  with_items:
    - "{{ kube_config_dir }}"
    - "{{ kube_config_temp_dir }}"
    - "{{ kube_script_dir }}"
    - "{{ kube_manifest_dir }}"
    - "{{ bin_dir }}"
    - "{{ kubelet_working_dir }}"
    - "{{ dir_extra_vars_stored }}"

#
# Install expect, rsync and conntrack.

- name: Install expect and rsync
  package: name={{ item }} state=present
  with_items:
    - "expect"
    - "rsync"
    - "conntrack"

#
# Save important parameters when kube-up, and may be used when upgrading.

- name: Check if extra vars directory exists in localhost
  local_action: stat path={{ local_dir_extra_vars_json_stored }}/{{ item }}
  register: dir_evs
  with_items:
    - "extra_vars.json"
    - "extra_vars.aliyun.json"
  run_once: true
  when: inventory_hostname in groups['masters']

- name: Save important parameters when kube-up
  copy: src={{ local_dir_extra_vars_json_stored }}/{{ item.item }} dest={{ dir_extra_vars_stored }}/{{ item.item }} force=yes
  when: inventory_hostname in groups['masters'] and item.stat.exists and item.stat.isreg
  with_items: "{{ dir_evs.results }}"

#
# Needed by kubelet/cadvisor.

- name: Enable cpuacct on CentOS
  lineinfile:
    dest: /etc/systemd/system.conf
    regexp: '^#?\s*DefaultCPUAccounting=.*$'
    line: 'DefaultCPUAccounting=yes'
    state: present
  when: ansible_distribution == "CentOS"

- name: Enable memacct on CentOS
  lineinfile:
    dest: /etc/systemd/system.conf
    regexp: '^#?\s*DefaultMemoryAccounting=.*$'
    line: 'DefaultMemoryAccounting=yes'
    state: present
  when: ansible_distribution == "CentOS"

- name: Reexec daemon on CentOS
  command: systemctl daemon-reexec
  when: ansible_distribution == "CentOS"

#
# Needed by ha master and ingress.

- name: Support ip_vs for keepalived | CentOS
  script: "ipvs/load-ipvs-centos.sh"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Support ip_vs for keepalived | Ubuntu
  script: "ipvs/load-ipvs-ubuntu.sh"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

#
# Misc preparations for bringing up cluster.

- name: Update /etc/hosts | Remove wrong registry hosts
  shell: newhosts=`mktemp` && sed -e '/.*{{ registry_prefix }}$/d' /etc/hosts > $newhosts && /bin/cp $newhosts /etc/hosts && /bin/rm $newhosts
  # lineinfile: dest=/etc/hosts regexp='.*{{ registry_prefix }}$' state=absent
  when: ensure_registry_hosts and registry_ip != ""

- name: Update /etc/hosts | Add registry hosts
  shell: echo "{{ registry_ip }} {{ registry_prefix }}" >> /etc/hosts
  # lineinfile: dest=/etc/hosts regexp='.*{{ registry_prefix }}$' line="{{ registry_ip }} {{ registry_prefix }}" state=present
  when: ensure_registry_hosts and registry_ip != ""

# Ensure `127.0.0.1 localhost` in /etc/hosts, apiserver bind to localhost ipv4
- name: Update /etc/hosts | Ensure localhost to 127.0.0.1
  shell: |-
    cat /etc/hosts | grep '^127\.0\.0\.1\s' || echo "127.0.0.1 localhost" >> /etc/hosts;
    cat /etc/hosts | grep '^127\.0\.0\.1\s\s*\(localhost\(\s\|$\)\|.*\slocalhost\(\s\|$\)\)' || ( newhosts=`mktemp` && sed -e '/^127\.0\.0\.1\s/ s/$/ localhost /' /etc/hosts > $newhosts && /bin/cp $newhosts /etc/hosts && /bin/rm $newhosts )

- name: Copy cloud-config to {{ kube_config_dir }}
  copy: src={{ cloud_config_dir }}/cloud-config dest={{ kube_config_dir }}/cloud-config
  when: host_provider == "aliyun" or host_provider == "anchnet"

- name: Write the global config file for all components
  template: src=config.j2 dest={{ kube_config_dir }}/config
  notify:
    - restart daemons

- name: Download and extract tar file from qiniu for all hosts
  include: qiniu.yml

- name: Install common CNI network plugins
  include: cni.yml
  when: network_plugins_cni

- name: Generate certs (or use ca-signed certs) and tokens
  include: secrets.yml

- name: Send docker config.json to all instances to pull image
  copy: src=docker-config.json dest={{ kubelet_working_dir }}/config.json
