---
# Base kubernetes tasks for all masters/nodes

- name: kubernetes base for installing
  include: install.yml
  when: k8s_op == "OP_INSTALL"

- name: kubernetes base for upgrading
  include: upgrade.yml
  when: k8s_op == "OP_UPGRADE"

- name: kubernetes base for downgrading
  include: downgrade.yml
  when: k8s_op == "OP_DOWNGRADE"
