---
# Generate self-signed certs or write ca-signed certs

- name: Create system kube-cert groups
  group: name={{ kube_cert_group }} state=present system=yes

- name: Create system kube user
  user:
    name=kube
    comment="Kubernetes user"
    shell=/sbin/nologin
    state=present
    system=yes
    groups={{ kube_cert_group }}

- name: Make sure the certificate directory exits
  file:
    path={{ kube_cert_dir }}
    state=directory
    mode=o-rwx
    group={{ kube_cert_group }}

- name: make sure the tokens directory exits
  file:
    path={{ kube_token_dir }}
    state=directory
    mode=o-rwx
    group={{ kube_cert_group }}

- include: gen_certs.yml
  when: inventory_hostname == groups['masters'][0]

- include: gen_tokens.yml
  when: inventory_hostname == groups['masters'][0]

- include: gen_basic_auth.yml
  when: inventory_hostname == groups['masters'][0]

- include: gen_abac_policy.yml
  when: inventory_hostname == groups['masters'][0]

- include: sync-certs.yml

- include: sync-tokens.yml
