apiVersion: v1
kind: Pod
metadata:
  name: mongo
  labels:
    name: mongo
spec:
  containers:
    - name: mongo
      image: mongo:3.0.5
      ports:
        - containerPort: 27017
      volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
  volumes:
    - name: mongo-storage
      anchnetPersistentDisk:
        volumeID: vol-I3BYQTKX
        fsType: ext4
