---
# Update hosts on master

- name: Update /etc/hosts file
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item]['internal_ip'] }} {{ item }}" state=present
  with_items: "{{ groups['nodes'] }}"
  notify:
    - restart apiserver
