---
# Update hosts on master

- name: Update /etc/hosts file
  shell: newhosts=`mktemp` && sed -e '/.*{{ item }}$/d' /etc/hosts > $newhosts && echo "{{ hostvars[item]['internal_ip'] }} {{ item }}" >> $newhosts && /bin/cp $newhosts /etc/hosts && /bin/rm $newhosts
  # lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item]['internal_ip'] }} {{ item }}" state=present
  with_items: "{{ groups['nodes'] }}"
  notify:
    - restart apiserver
