---
# Main tasks for installing etcd.

#
# Prepare installation.

- name: Override etcd config file directory for upstart
  set_fact:
    etcd_config_dir: "/etc/default"
  when: kubernetes_use_upstart

- name: Create etcd config directory
  file: path={{ etcd_config_dir }} state=directory

- name: Create etcd data directory
  file: path={{ item }} state=directory
  with_items:
    - "{{ etcd_data_dir }}"
    - "{{ etcd_events_dir }}"

#
# Install etcd and create configuration file.

- name: Install etcd from qiniu
  include: qiniu.yml

- name: Write etcd config file
  template: src=etcd-server{{ item }}.conf.j2 dest={{ etcd_config_dir }}/etcd-server{{ item }}.conf
  with_items:
    - ""
    - "-events"
  notify:
    - restart etcd

- name: Create upstart script for upstart based distribution
  template: src=etcd-server{{ item }}.upstart.j2 dest=/etc/init/etcd-server{{ item }}.conf
  with_items:
    - ""
    - "-events"
  notify:
    - restart etcd
  when: kubernetes_use_upstart

- name: Write etcd systemd unit file for systemd based distribution
  template: src=etcd-server{{ item }}.service.j2 dest=/etc/systemd/system/etcd-server{{ item }}.service
  with_items:
    - ""
    - "-events"
  notify:
    - reload systemd
    - restart etcd
  when: not kubernetes_use_upstart

#
# Enable and start etcd.

- name: Reload systemd if etcd systemd unit file changed
  command: systemctl --system daemon-reload
  when: not kubernetes_use_upstart

- name: Enable etcd
  service: name=etcd-server{{ item }} enabled=yes
  with_items:
    - ""
    - "-events"

- name: Start etcd-server
  service: name=etcd-server state=started
  register: etcd_server_started

- name: Start etcd-server-events
  service: name=etcd-server-events state=started
  register: etcd_server_events_started
