---
# Install runtime dependencies and record operation log.

#
# Install runtime dependencies.

- name: Install runtime dependencies
  include: install_runtime.yml
  when: k8s_op == "OP_INSTALL"

#
# Record operation log.

- name: Make sure log directory exists
  file: path={{ kube_config_dir }}/log state=directory

- name: Make sure operation log file exists
  file: path={{ kube_config_dir }}/log/operation state=touch

- name: Record operation log
  lineinfile: dest={{ kube_config_dir }}/log/operation line="[{{ ansible_date_time.date }} {{ ansible_date_time.time }}] operation '{{ k8s_op }}', version '{{ kube_base_version }}+{{ kube_caicloud_version }}'" insertafter=EOF state=present
