---
# Tasks for the control machine.

- name: Fetch kubectl and kubeconfig
  include: fetch.yml

# Consider running in a container, so add mapping again.
- name: Check if add mapping into /etc/hosts
  include: add_mapping.yml
  when: k8s_op != "OP_UNINSTALL"
