---
# Install kubernetes node.

#
# Prepare installation.

- name: Set selinux permissive because tokens and selinux does not work together
  selinux: state=permissive policy={{ ansible_selinux.type }}
  when: ansible_selinux is defined and ansible_selinux.status == "enabled"

- name: Make sure manifest directory exists
  file: path={{ kube_manifest_dir }} state=directory

#
# Find tokens for master and nodes instances.

- name: Get the node token values
  slurp:
    src: "{{ kube_token_dir }}/{{ item }}-{{ inventory_hostname }}.token"
  with_items:
    - "system:kubelet"
    - "system:proxy"
  register: tokens
  delegate_to: "{{ groups['masters'][0] }}"

- name: Set token facts
  set_fact:
    kubelet_token: "{{ tokens.results[0].content|b64decode }}"
    proxy_token: "{{ tokens.results[1].content|b64decode }}"

#
# Install init scripts for all components.

- name: Install node config files for upstart-based distribution
  include: upstart-service.yml
  when: kubernetes_use_upstart

- name: Install node config files for systemd-based distribution
  include: systemd-service.yml
  when: not kubernetes_use_upstart

- name: Write the delay-node-services target for systemd
  copy: src=systemd/delay-node-services.target dest=/etc/systemd/system/ mode=0644
  when: not kubernetes_use_upstart

- name: Enable delay-node-services for systemd
  service: name=delay-node-services.target enabled=yes
  when: not kubernetes_use_upstart

#
# Install kubelet.

- name: Write the config files for kubelet
  template: src=kubelet.j2 dest={{ kube_config_dir }}/kubelet
  notify:
    - restart kubelet

- name: Write the kubecfg (auth) file for kubelet
  template: src=kubelet.kubeconfig.j2 dest={{ kube_config_dir }}/kubelet.kubeconfig
  notify:
    - restart kubelet

- name: Start kubelet
  service: name=kubelet enabled=yes state=started
  register: node_kubelet_started

#
# Install kube-proxy.

- name: Write the config files for proxy
  template: src=proxy.j2 dest={{ kube_config_dir }}/proxy
  notify:
    - restart proxy

- name: Write the kubecfg (auth) file for kube-proxy
  template: src=proxy.kubeconfig.j2 dest={{ kube_config_dir }}/proxy.kubeconfig
  notify:
    - restart proxy

- name: Start proxy
  service: name=kube-proxy enabled=yes state=started
  register: proxy_started
