apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/cluster-service: "true"
  name: monitoring
  namespace: kube-system
spec:
  ports:
  - port: 80
    targetPort: 6090
  selector:
    k8s-app: monitoring-server
