apiVersion: v1
kind: LimitRange
metadata:
  name: kube-system
  namespace: kube-system
  labels:
    kubernetes-admin.caicloud.io/type: partition
spec:
  limits:
  - default:
      cpu: 100m
      memory: 100Mi
    defaultRequest:
      cpu: 100m
      memory: 100Mi
    max:
      cpu: 1000m
      memory: 1Gi
    type: Container
