apiVersion: v1
kind: ResourceQuota
metadata:
  name: cyclone
  namespace: cyclone
  labels:
    kubernetes-admin.caicloud.io/type: partition
    kubernetes-admin.caicloud.io/partition: cyclone
spec:
  hard:
    cpu: "4"
    limits.cpu: "8"
    limits.memory: 8Gi
    memory: 4Gi
